name: Windows Build

run-name: Build Windows versions of MeshAgent

on:
  push:
  pull_request:

jobs:
  windows-build:
    runs-on: ${{ matrix.platform == 'ARM64' && 'windows-11-arm' || 'windows-latest' }}
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, x86, ARM64]
    steps:
    - uses: actions/checkout@v7
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v3
    - name: List installed VS components
      run: vswhere.exe -all -products * -format json
